### ISSUE TITLE
Better Meta tags 

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-councilmatic#118] opened 2015-10-16 17:10 UTC
Right now, the default text in google search results are pretty bad
<img width="512" alt="screen_shot_2015-10-16_at_12 02 31_pm_1024" src="https://cloud.githubusercontent.com/assets/536941/10548247/ea3af482-73fe-11e5-8aec-09996e5cd5e0.png">

**Comment by derekeder** [comment] 2015-10-16 17:13
This is a dupe of #107

**Closed as completed by derekeder** 2015-10-16 17:13 UTC
Labels: SEO
