### ISSUE TITLE
set TEMPLATES settings dynamically depending on whether DEBUG is True

### ISSUE THREAD

**Issue by mccc** [datamade/nyc-councilmatic#166] opened 2016-04-08 17:10 UTC
If DEBUG is True, we want APP_DIRS to be True; if not , we want to define 'loaders' as in NYC Councilmatic (see link below)

https://github.com/datamade/nyc-councilmatic/blob/master/councilmatic/settings.py#L73

**Comment by cathydeng** [comment] 2016-04-13 14:52
duplicate of #165

**Closed as completed by cathydeng** 2016-04-13 14:52 UTC
